# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/stira/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: lts-16.0
extra-deps:
    - cabal-helper-0.7.3.0
    - djinn-ghc-0.0.2.3
    - djinn-lib-0.0.1.3
    - fclabels-2.0.5
    - ghc-syb-utils-0.2.3.3
