#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    spacevim_guifont = "NotoEmoji Nerd Font Mono:h11"

    bootstrap_before = "myspacevim#before" 
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

#=================================
# language layers
#=================================

# lua
[[layers]]
  name = "lang#lua"

# javascript
[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

# typescript  
[[layers]]
  name = "lang#typescript"
  typescript_server_path = "$HOME/.local/bin"

# fuzzy search
[[layers]]
name = "denite"

# custom plugins
[[custom_plugins]]
    name = "lilydjwg/colorizer"
    merged = false

